"""empty message

Revision ID: 744f24095078
Revises: 32bed261cab8
Create Date: 2019-03-31 23:44:50.322360

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '744f24095078'
down_revision = '32bed261cab8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stocks', sa.Column('price_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stocks', 'price_date')
    # ### end Alembic commands ###
