"""empty message

Revision ID: 7ea77669c0ff
Revises: 
Create Date: 2019-03-28 01:04:44.862948

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7ea77669c0ff'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stocks',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('stock_name', sa.String(length=60), nullable=False),
    sa.Column('opening_price', sa.Float(), nullable=False),
    sa.Column('closing_price', sa.Float(), nullable=False),
    sa.Column('highest_price', sa.Float(), nullable=False),
    sa.Column('lowest_price', sa.Float(), nullable=False),
    sa.Column('number_of_shares', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('first_name', sa.String(length=60), nullable=False),
    sa.Column('last_name', sa.String(length=60), nullable=False),
    sa.Column('email', sa.String(length=60), nullable=False),
    sa.Column('is_admin', sa.Enum('yes', 'no', name='isadmin'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('stocks')
    op.execute("DROP TYPE isadmin")
    # ### end Alembic commands ###
