"""Module for Base Model"""
from datetime import datetime

from sqlalchemy.dialects.postgresql import UUID

from .mixins import ModelMixin
from .config import db


class BaseModel(db.Model, ModelMixin):
    """Base model for all database models.

    attributes:
        id (string, reserved):
             a unique identifier for each instance. Autogenerated.
    """

    __abstract__ = True

    id = db.Column(UUID(), primary_key=True)
    created_at = db.Column(db.DateTime, default=datetime.utcnow)
    updated_at = db.Column(db.DateTime, onupdate=datetime.utcnow)
    created_by = db.Column(db.String, nullable=True)
    updated_by = db.Column(db.String, nullable=True)
