"""Module for Base Model"""
import uuid

from datetime import datetime

from sqlalchemy.dialects.postgresql import UUID

from .mixins import ModelMixin
from .config import db


class BaseModel(db.Model, ModelMixin):
    """Base model for all database models.

    attributes:
        id (string, reserved):
             a unique identifier for each instance. Autogenerated.
    """

    __abstract__ = True

    id = db.Column(
        UUID(as_uuid=True), primary_key=True,
        nullable=False, default=uuid.uuid4
    )
    created_at = db.Column(db.DateTime, default=datetime.utcnow)
    updated_at = db.Column(db.DateTime, onupdate=datetime.utcnow)
